language: ruby

rvm:
  - 1.9.3

env:
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.2
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.1.1
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.1
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.0.2
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.0.1

install:
  - gem install bundler
  - gem install thread_safe
  - gem install minitest
  - gem install io-console
  - gem install atomic
  - gem install bigdecimal
  - gem install mocha
  - sudo apt-get update
  - sudo apt-get install libtool libxml2 openssl sqlite
  - sudo apt-get install rbenv
  #- rbenv install 1.9.3-p392
  #- rbenv global 1.9.3-p392
  #- rbenv rehash
  - gem install nuodb
  - gem install activerecord-nuodb-adapter
  - gem install rails -v "=3.2.8"

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - lbayas@nuodb.com

before_install:
  - wget http://www.nuodb.com/latest/releases/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - sudo chmod 777 active_setup_linux.sh

before_script:
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password baz --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password baz &
  - sleep 2
  - echo "create user cloud password 'user';" | ${NUODB_ROOT}/bin/nuosql test@localhost --user dba --password baz
  - sleep 10

script:
  - ./active_setup_linux.sh
  - ARCONN=nuodb ruby -I~/tmpy/rails-latest/:~/tmpy/rails-latest/activerecord/test/:/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/mocha-0.14.0/lib/ ~/tmpy/rails-latest/activerecord/test/cases/migration_test.rb

after_script:
  - sudo dpkg -r nuodb
